### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by gotshadowbantempaccount** [traPtitech/markdown-it-spoiler#42]
.use(require('markdown-it-spoiler'))   ? return error

**Comment by sapphi-red** [comment]
Yes.
It should work.
Please try to provide a minimum reproduce.

**Comment by gotshadowbantempaccount** [comment]
try also: $ npm i @traptitech/markdown-it-spoiler --save

This dependency was not found:

* /markdown-it-spoiler in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/Editor.vue

To install it, you can run: npm install --save /markdown-it-spoiler

**Comment by sapphi-red** [comment]
I got it.
```js
.use(require('markdown-it-spoiler'))
```
is not correct.
You should do
```js
.use(require('@traptitech/markdown-it-spoiler'))
```

**Comment by gotshadowbantempaccount** [comment]
ok solved when install by $ npm i @traptitech/markdown-it-spoiler it dosnt save to **nod_module** folder when copy it manually it star to work strange thx
